[build]
  command = "echo 'Static site - no build required'"
  publish = "."
  functions = "functions"

[dev]
  framework = "#static"
  targetPort = 3000
  autoLaunch = true

[context.production.environment]
  NODE_VERSION = "18"
  SECURE = "true"
  CACHE_CONTROL = "max-age=3600, public"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Basic-Auth = "admin:$2a$12$jaGMxtjEVdewLl0mEjc83O3ZLfD1vgPwZqKfH.tpP3quw0UMRthbK"
    X-Robots-Tag = "noindex, nofollow"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["fs", "path"]
  included_files = ["videos.json"]

[[plugins]]
  package = "@netlify/plugin-labs"
  [plugins.inputs]
    enableIdentity = true
