[build]
  command = "echo 'No build needed'"
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    Basic-Auth = "$2a$12$VOBKojttjGaIJv3RoE5JSOsMPXx7fbL9mjvL/Ci5EYbeo0F5dqHua"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
