[build]
  command = "echo 'No build needed'"
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    Basic-Auth = "admin:$2a$12$8Bwgd53bAuglSbQemwHXBOxfdT3ZjUDDoigmX5eig3/ipAA8FXQ/q"  # Replace with your generated hash

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"
